name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./Implementation
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'
      - run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: |
          cd Implementation
          python tests.py
